// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqcdfqmVA2o4E9rD10Qn_C1gnuGpf7iIU',
    appId: '1:39140196012:web:df2d044382d40bea656909',
    messagingSenderId: '39140196012',
    projectId: 'studytrack-478ab',
    authDomain: 'studytrack-478ab.firebaseapp.com',
    storageBucket: 'studytrack-478ab.firebasestorage.app',
    measurementId: 'G-4Z6XJJZQSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBezYrLjqEUnwN05ZeC9U26iaHEQGV5r5Y',
    appId: '1:39140196012:android:bb3a6a736af81593656909',
    messagingSenderId: '39140196012',
    projectId: 'studytrack-478ab',
    storageBucket: 'studytrack-478ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ3I_lP5kon4LFRPBh4NLdBr54FvVJgsM',
    appId: '1:39140196012:ios:01069bcfd95c0187656909',
    messagingSenderId: '39140196012',
    projectId: 'studytrack-478ab',
    storageBucket: 'studytrack-478ab.firebasestorage.app',
    iosBundleId: 'com.example.studyTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ3I_lP5kon4LFRPBh4NLdBr54FvVJgsM',
    appId: '1:39140196012:ios:01069bcfd95c0187656909',
    messagingSenderId: '39140196012',
    projectId: 'studytrack-478ab',
    storageBucket: 'studytrack-478ab.firebasestorage.app',
    iosBundleId: 'com.example.studyTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqcdfqmVA2o4E9rD10Qn_C1gnuGpf7iIU',
    appId: '1:39140196012:web:29bf3d9cd8f7e6f0656909',
    messagingSenderId: '39140196012',
    projectId: 'studytrack-478ab',
    authDomain: 'studytrack-478ab.firebaseapp.com',
    storageBucket: 'studytrack-478ab.firebasestorage.app',
    measurementId: 'G-J3WE7VSFE0',
  );
}
